[package]
name = "bitcoin-waila"
version = "0.2.3"
edition = "2018"
authors = ["Ben Carman <benthecarman@live.com>", "Paul Miller <paul@pauljmiller.com>"]
license = "MIT"
homepage = "https://github.com/MutinyWallet/bitcoin-waila/"
repository = "https://github.com/MutinyWallet/bitcoin-waila/"
readme = "README.md"
documentation = "https://docs.rs/bitcoin-waila/"
description = "\"What am I looking at?\" A tool for decoding bitcoin-related strings."
keywords = ["lightning", "bitcoin", "bip21", "lnurl"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin = { version = "0.29.2", default-features = false, features = ["serde"] }
bip21 = "0.2.0"
nostr = { version = "=0.23.0-bitcoin-v0.29", default-features = false, features = ["nip19"] }
lnurl-rs = { version = "0.3", default-features = false }
lightning-invoice = { version = "0.26.0", default-features = false }
lightning = { version = "0.0.118", default-features = false }
rgb-std = { version = "0.10.4", optional = true }
rgb-wallet = { version = "0.10.4", optional = true }
url = "2.4.1"

[features]
default = ["std"]
std = ["bitcoin/std", "lightning-invoice/std", "lightning/std"]
no-std = ["bitcoin/no-std", "lightning-invoice/no-std", "lightning/no-std"]
rgb = ["rgb-std", "rgb-wallet"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
