name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-formatting-v2-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-formatting-v2-
            cargo-${{ runner.os }}-

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-10-24
          components: rustfmt
          profile: minimal

      - name: Check formatting
        run: |
          cargo +nightly-2023-10-24 fmt -- --check

      - name: Check docs
        run: cargo +nightly-2023-10-24 doc

  core_tests_linux:
    name: Core Tests on Linux
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-10-24
          override: true
          profile: minimal
          components: clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-core-tests-linux-v2-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-core-tests-linux-v2-
            cargo-${{ runner.os }}-

      - name: Add targets
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Run cargo clippy
        run: cargo clippy --all-features --tests --package bitcoin-waila --target=x86_64-unknown-linux-gnu -- -D warnings

      - name: Run cargo test
        run: cargo test --package bitcoin-waila --target=x86_64-unknown-linux-gnu --all-features
